repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: debug-statements
      - id: fix-encoding-pragma
        args:
          [
              "--remove", # Remove encoding line
          ]
      - id: mixed-line-ending
#      - id: no-commit-to-branch
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
              "-rn", # Only display messages
              "-sn", # Don't display the score
              "--rcfile", "pyproject.toml",
          ]
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
      - id: pyupgrade
        args: ["--py310-plus"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.942"
    hooks:
      - id: mypy

ci:
  skip: [pylint]
